**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [13]:
#Code here
a=np.zeros(10)
np.put(a,[4],[1])
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [18]:
#Code here
a = int(input("Enter number of rows"))
b = int(input("Enter number of columns"))
matrix = np.random.random(a*b).reshape(a,b)*100
average = np.average(matrix)
print(matrix)
print("Average is ", average)

[[28.28685627 89.15146571 43.01481155 98.95603367]
 [92.63159739 65.71258329 46.97980421 87.72080477]
 [12.05461042 41.42110086 11.87917244 81.7244186 ]]
Average is  58.29443826590873


###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [30]:
#Code here
rows = int(input("Enter rows"))
column = int(input("Enter columns"))
matrix = np.ones((rows,column))
matrix[1:rows-1,1:column-1] = 0
print(matrix)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [37]:
#Code here
vector = np.linspace(1/11,10/11,10)
print(vector)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [ ]:
#Code here
# No we can't, Identity matrix only be formed of a N X N matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [45]:
#Code here
matrix = np.linspace(0,4,25,dtype=np.int8).reshape(5,5)
print(matrix)

[[0 0 0 0 0]
 [0 1 1 1 1]
 [1 1 2 2 2]
 [2 2 2 3 3]
 [3 3 3 3 4]]


###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [ ]:
#code here


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
#Code here

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [ ]:
#Code here
a = input().split()
result = np.array(a,dtype=np.float32)
result = np.sort(a)[::-1]
print(result)


<class 'numpy.ndarray'>
['5' '4' '3' '2' '1']


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [20]:
#Code here
a = np.array([0,0,0,0,0])
result = len(a)
print(f"elemtns_count : {result}")

elemtns_count : 5


### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [23]:
#Code here
def softmax(array):
    if array.ndim !=1:
        return "Not a Vector"
    else:
        result = np.exp(array)/np.sum(np.exp(array))
        return result
input = np.array([86.03331084,37.7285648,48.64908087,87.16563062,38.40852563,37.20006318])
print(softmax(input))

[2.43733248e-01 2.56112114e-22 1.41628283e-17 7.56266752e-01
 5.05514197e-22 1.50974911e-22]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [28]:
#Coder here
def nvstack(*array):
    if isinstance(array,np.ndarray):
        return "Not a Numpy Array"
    else:
        result = np.vstack(array)
        return result

a= [[0,1,2,3,4],
 [5,6,7,8,9]]

b= [[1,1,1,1,1],
 [1,1,1,1,1]]

c= [[0, 1 ,2 ,3 ,4],
 [5 ,6 ,7 ,8 ,9]]

d= [[1, 1, 1, 1, 1],
 [1 ,1 ,1 ,1 ,1]]

e= [[0.10117373 ,0.1677244 , 0.73764059 ,0.83166097 ,0.48985695],
 [0.44581567 ,0.13502419, 0.55692335, 0.16479622 ,0.61193593]]
print(nvstack(c,d,e))

[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]


### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [32]:
#Code here
def date_array(start:str, end:str):
    date = np.arange(np.datetime64(start),np.datetime64(end)+1, dtype=np.datetime64)
    return date
print(date_array(start="2020-09-15",end="2020-09-25"))


['2020-09-15' '2020-09-16' '2020-09-17' '2020-09-18' '2020-09-19'
 '2020-09-20' '2020-09-21' '2020-09-22' '2020-09-23' '2020-09-24'
 '2020-09-25']


###`Q-14:` Subtract the mean of each row from a matrix.

In [ ]:
#code here

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [44]:
#Code here
a = np.arange(1,11).reshape(5,2)
print(a)
result = a[:,[1,0]]
result


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9]])

###`Q-16:` Replace odd elements in arrays with -1.

In [45]:
#Code here
a = np.arange(1,11).reshape(5,2)
result = np.where(a%2!=0,-1,a)
print(result)

[[-1  2]
 [-1  4]
 [-1  6]
 [-1  8]
 [-1 10]]


###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [53]:
#Code here
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])
result = np.maximum(a,b)
print(result)

[6 3 1 7 8]


###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [54]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
arr1

array([[8552, 2213, 1337, 3249, 3018],
       [7212, 6832, 8825,    6, 8066],
       [4940, 9138, 1408, 3042, 9922],
       [2938,   40, 3216, 8737, 9864],
       [1539, 9147, 2642, 3149, 2867],
       [6038, 8424, 2345, 8411, 3436],
       [1591, 8291, 7391, 8247, 4371],
       [9138, 4576, 5902,  222,  392]], dtype=int32)

In [57]:
#Code here
def normalize(array):
    return (array - np.min(array))/(np.max(array)-np.min(array))
# 1st 
result = arr1[:,::2]
print(result)
#2nd
print(normalize(arr1))

[[8552 1337 3018]
 [7212 8825 8066]
 [4940 1408 9922]
 [2938 3216 9864]
 [1539 2642 2867]
 [6038 2345 3436]
 [1591 7391 4371]
 [9138 5902  392]]
[[0.86183945 0.22256958 0.13422751 0.3270472  0.30375151]
 [0.72670432 0.68838241 0.88937071 0.         0.81282775]
 [0.49757967 0.92093586 0.14138766 0.30617184 1.        ]
 [0.29568374 0.0034288  0.32371924 0.88049617 0.99415087]
 [0.15459863 0.92184349 0.265833   0.31696248 0.2885236 ]
 [0.6083098  0.84893102 0.2358814  0.84762001 0.34590561]
 [0.15984268 0.83551835 0.74475595 0.83108108 0.44019766]
 [0.92093586 0.46087132 0.59459459 0.02178298 0.03892699]]


###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [ ]:
#Code here

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [ ]:
#code here