In [2]:
# np.Array
import numpy as np
#vector
a = np.array([1,2,3,5])
print(a)

[1 2 3 5]


In [3]:
#matrix
b = np.array([[1,2,4,5,6],[1,2,4,5,6]])
print(b)

[[1 2 4 5 6]
 [1 2 4 5 6]]


In [4]:
#3d numpy array is called tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
#dtype
d= np.array([0,2,4,5,6],dtype=float)
print(d)

[0. 2. 4. 5. 6.]


In [23]:
#np.arange
np.arange(1,11,2)
#with reshape
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [25]:
#np.ones and np.zeros
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.random.random((3,4))

array([[0.94363624, 0.06779822, 0.9989656 , 0.8881716 ],
       [0.541186  , 0.26867485, 0.94696995, 0.10310322],
       [0.40840552, 0.68529583, 0.80473281, 0.59966018]])

In [28]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
c.ndim

3

In [33]:
c.shape

(2, 2, 2)

In [34]:
c.size

8

In [35]:
c.itemsize

8

In [36]:
print(c.dtype)

int64


In [37]:
c.astype(np.int8)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int8)

### Array   Operations

In [38]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
# scalar operations
#arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
#relational operators
a2==14

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [45]:
#vector operations
#arithmatic

a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])