In [1]:
# NP.SORT
import numpy as np
a = np.random.randint(1,100,15)
a 

array([63, 26, 61, 49, 70, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49],
      dtype=int32)

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[28, 34, 71, 44],
       [46, 35, 49, 68],
       [86, 59, 78, 69],
       [96, 30,  8, 91],
       [50, 89, 60,  3],
       [42, 46,  1, 91]], dtype=int32)

In [6]:
np.sort(a)[::-1]

array([93, 88, 70, 63, 61, 52, 49, 49, 44, 33, 31, 26, 26, 22,  5],
      dtype=int32)

In [5]:
np.sort(b,axis=0)

array([[28, 30,  1,  3],
       [42, 34,  8, 44],
       [46, 35, 49, 68],
       [50, 46, 60, 69],
       [86, 59, 71, 91],
       [96, 89, 78, 91]], dtype=int32)

In [8]:
# NP.APPEND

np.append(a,200)

array([ 63,  26,  61,  49,  70,  44,  93,  33,  31,  52,  26,   5,  22,
        88,  49, 200])

In [11]:
np.append(b,np.zeros((b.shape[0],1)),axis=1)

array([[28., 34., 71., 44.,  0.],
       [46., 35., 49., 68.,  0.],
       [86., 59., 78., 69.,  0.],
       [96., 30.,  8., 91.,  0.],
       [50., 89., 60.,  3.,  0.],
       [42., 46.,  1., 91.,  0.]])

In [12]:
# NP.CONCATENATE
c = np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [15]:
# NP.UNIQUE
e = np.array([1,1,2,2,4,4,3,3,5,6,7,8,9,9])
np.unique(e)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# NP.EXPAND_DIMS
a

array([63, 26, 61, 49, 70, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49],
      dtype=int32)

In [20]:
np.expand_dims(a,axis=0).shape


(1, 15)

In [21]:
# NP.WHERE
a

array([63, 26, 61, 49, 70, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49],
      dtype=int32)

In [28]:
np.where(a>50,1,a)

array([ 1, 26,  1, 49,  1, 44,  1, 33, 31,  1, 26,  5, 22,  1, 49],
      dtype=int32)

In [29]:
# NP.ARGMAX
a

array([63, 26, 61, 49, 70, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49],
      dtype=int32)

In [30]:
np.argmax(a)

np.int64(6)

In [32]:
np.argmax(b,axis=1)

array([2, 3, 0, 0, 1, 3])

In [33]:
# NP.ARGMIN
np.argmin(a)

np.int64(11)

In [34]:
# NP.CUMSUM
a

array([63, 26, 61, 49, 70, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49],
      dtype=int32)

In [35]:
np.cumulative_sum(a)

array([ 63,  89, 150, 199, 269, 313, 406, 439, 470, 522, 548, 553, 575,
       663, 712])

In [42]:
np.cumsum(b,axis=1)
np.cumprod(a)

array([                  63,                 1638,                99918,
                    4895982,            342718740,          15079624560,
              1402405084080,       46279367774640,     1434660401013840,
          74602340852719680,  1939660862170711680, -8748439762855993216,
       -7998234045736334592, -2868321223834482688,  7026212621786761216])

In [43]:
# NP.PERCENTILE
a

array([63, 26, 61, 49, 70, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49],
      dtype=int32)

In [46]:
np.percentile(a,50)

np.float64(49.0)

In [50]:
# NP.HISTOGRAM
np.histogram(a,bins=[0,50,100])

(array([9, 6]), array([  0,  50, 100]))

In [55]:
# NP.CORRCOEF
salary = np.array([100,200,300,400,500,600])
experience = np.array([1,2,3,4,5,6])
np.corrcoef(salary,experience)

array([[1., 1.],
       [1., 1.]])

In [56]:
# NP.ISIN
a

array([63, 26, 61, 49, 70, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49],
      dtype=int32)

In [58]:
a[np.isin(a,[63,26,61,8,9,0,10])]

array([63, 26, 61, 26], dtype=int32)

In [59]:
# NP.FLIP
a

array([63, 26, 61, 49, 70, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49],
      dtype=int32)

In [60]:
np.flip(a)

array([49, 88, 22,  5, 26, 52, 31, 33, 93, 44, 70, 49, 61, 26, 63],
      dtype=int32)

In [61]:
b

array([[28, 34, 71, 44],
       [46, 35, 49, 68],
       [86, 59, 78, 69],
       [96, 30,  8, 91],
       [50, 89, 60,  3],
       [42, 46,  1, 91]], dtype=int32)

In [64]:
np.flip(b,axis=1)

array([[44, 71, 34, 28],
       [68, 49, 35, 46],
       [69, 78, 59, 86],
       [91,  8, 30, 96],
       [ 3, 60, 89, 50],
       [91,  1, 46, 42]], dtype=int32)

In [65]:
# NP.PUT
a

array([63, 26, 61, 49, 70, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49],
      dtype=int32)

In [66]:
np.put(a,[0,1],[110,530])

In [67]:
a

array([110, 530,  61,  49,  70,  44,  93,  33,  31,  52,  26,   5,  22,
        88,  49], dtype=int32)

In [68]:
# NP.DELETE
a

array([110, 530,  61,  49,  70,  44,  93,  33,  31,  52,  26,   5,  22,
        88,  49], dtype=int32)

In [71]:
np.delete(a,[0,1,2,4])

array([49, 44, 93, 33, 31, 52, 26,  5, 22, 88, 49], dtype=int32)

In [72]:
a

array([110, 530,  61,  49,  70,  44,  93,  33,  31,  52,  26,   5,  22,
        88,  49], dtype=int32)

### Set Functions
- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [73]:
# NP.CLIP
a

array([110, 530,  61,  49,  70,  44,  93,  33,  31,  52,  26,   5,  22,
        88,  49], dtype=int32)

In [75]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 61, 49, 70, 44, 75, 33, 31, 52, 26, 25, 25, 75, 49],
      dtype=int32)