In [2]:
# np.Array
import numpy as np
#vector
a = np.array([1,2,3,5])
print(a)

[1 2 3 5]


In [3]:
#matrix
b = np.array([[1,2,4,5,6],[1,2,4,5,6]])
print(b)

[[1 2 4 5 6]
 [1 2 4 5 6]]


In [4]:
#3d numpy array is called tensor
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [14]:
#dtype
d= np.array([0,2,4,5,6],dtype=float)
print(d)

[0. 2. 4. 5. 6.]


In [3]:
#np.arange
np.arange(1,11,2)
#with reshape
# np.arange(1,11).reshape(2,5)

array([1, 3, 5, 7, 9])

In [25]:
#np.ones and np.zeros
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [27]:
np.random.random((3,4))

array([[0.94363624, 0.06779822, 0.9989656 , 0.8881716 ],
       [0.541186  , 0.26867485, 0.94696995, 0.10310322],
       [0.40840552, 0.68529583, 0.80473281, 0.59966018]])

In [28]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
c.ndim

3

In [33]:
c.shape

(2, 2, 2)

In [34]:
c.size

8

In [35]:
c.itemsize

8

In [36]:
print(c.dtype)

int64


In [37]:
c.astype(np.int8)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int8)

### Array   Operations

In [38]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
# scalar operations
#arithmetic
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [43]:
#relational operators
a2==14

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [45]:
#vector operations
#arithmatic

a1+a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

### Array Functions


In [47]:
a1= np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[93., 74.,  4.],
       [66., 64., 42.],
       [17., 36., 72.]])

In [54]:
 #max/min/sum/prod
# axis =0 -> column and 1 -> row
a = np.min(a1,axis=1)
print(a)

[ 4. 42. 17.]


In [60]:
#mean/median/std/var
np.var(a1,axis=0)

array([989.55555556, 258.66666667, 774.22222222])

In [61]:
# trigonometric functions
np.sin(a1)

array([[-0.94828214, -0.98514626, -0.7568025 ],
       [-0.02655115,  0.92002604, -0.91652155],
       [-0.96139749, -0.99177885,  0.25382336]])

In [62]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [64]:
# log and exponents
np.exp(a1)

array([[2.45124554e+40, 1.37338298e+32, 5.45981500e+01],
       [4.60718663e+28, 6.23514908e+27, 1.73927494e+18],
       [2.41549528e+07, 4.31123155e+15, 1.85867175e+31]])

In [69]:
# round/floor/ceil
np.ceil(np.random.random((2,3))*100)

array([[ 5., 62., 60.],
       [46., 93., 53.]])

### Indexing / Slicing


In [72]:
a1= np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [73]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a1[-1]

np.int64(9)

In [75]:
a1[0]

np.int64(0)

In [76]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
a2[1][2]

np.int64(6)

In [78]:
a2[1,1]

np.int64(5)

In [79]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [80]:
a3[1,1,1]

np.int64(7)

In [81]:
a3[0,1,1]

np.int64(3)

In [82]:
a1[:4]

array([0, 1, 2, 3])

In [83]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
a1[2:5]

array([2, 3, 4])

In [85]:
a1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [86]:
a1[5:]

array([5, 6, 7, 8, 9])

In [87]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [88]:
a2[0,:]

array([0, 1, 2, 3])

In [90]:
a2[:,2]

array([ 2,  6, 10])

In [91]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [92]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [99]:
a2[0:2,1:4]

array([[1, 2, 3],
       [5, 6, 7]])

In [101]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [102]:
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [103]:
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [105]:
a3[0,1,:]

array([3, 4, 5])

In [106]:
a3[1,:,1]

array([10, 13, 16])

In [107]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [108]:
a3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [110]:
a3[::2,0:1,::2]

array([[[ 0,  2]],

       [[18, 20]]])

### Iterating

In [111]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [113]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [120]:
for i in a2:
    for j in i:
        print(j,end=" ")
    print()

0 1 2 3 
4 5 6 7 
8 9 10 11 


In [123]:
for i in a3:
    for j in i:
        for k in j:
            print(k,end=" ")
        print()
    print()

0 1 2 
3 4 5 
6 7 8 

9 10 11 
12 13 14 
15 16 17 

18 19 20 
21 22 23 
24 25 26 



In [125]:
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping


In [126]:
# transpose
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [127]:
np.transpose(a3)

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [128]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [134]:
# reval
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [138]:
# Stacking
# Horizontal Stacking 
a4= np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a6=np.hstack((a4,a5))
a6
# vertical Stacking
a4= np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)
a6=np.vstack((a4,a5))
a6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Spitting

In [142]:
# horizontal
np.split(a6,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]